[2025-04-17T16:57:36.225+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T16:57:36.234+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw8_create_pinecone_index.create_pinecone_index manual__2025-04-17T16:52:34.831111+00:00 [queued]>
[2025-04-17T16:57:36.238+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw8_create_pinecone_index.create_pinecone_index manual__2025-04-17T16:52:34.831111+00:00 [queued]>
[2025-04-17T16:57:36.238+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-04-17T16:57:36.245+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_pinecone_index> on 2025-04-17 16:52:34.831111+00:00
[2025-04-17T16:57:36.251+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'hw8_create_pinecone_index', 'create_pinecone_index', 'manual__2025-04-17T16:52:34.831111+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/hw8_2_create_pinecone_index.py', '--cfg-path', '/tmp/tmpf_47g_3a']
[2025-04-17T16:57:36.253+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1314) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-17T16:57:36.253+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask create_pinecone_index
[2025-04-17T16:57:36.253+0000] {standard_task_runner.py:72} INFO - Started process 1315 to run task
[2025-04-17T16:57:36.291+0000] {task_command.py:467} INFO - Running <TaskInstance: hw8_create_pinecone_index.create_pinecone_index manual__2025-04-17T16:52:34.831111+00:00 [running]> on host 18d9c2a33fd7
[2025-04-17T16:57:36.342+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hw8_create_pinecone_index' AIRFLOW_CTX_TASK_ID='create_pinecone_index' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T16:52:34.831111+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T16:52:34.831111+00:00'
[2025-04-17T16:57:36.342+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-17T16:57:36.352+0000] {logging_mixin.py:190} INFO - Error importing pinecone: The official Pinecone python package has been renamed from `pinecone-client` to `pinecone`. Please remove `pinecone-client` from your project dependencies and add `pinecone` instead. See the README at https://github.com/pinecone-io/pinecone-python-client for more information on using the python SDK.
[2025-04-17T16:57:36.352+0000] {logging_mixin.py:190} INFO - Attempting to import pinecone_client instead...
[2025-04-17T16:57:36.353+0000] {logging_mixin.py:190} INFO - Both import attempts failed. Error: No module named 'pinecone_client'
[2025-04-17T16:57:36.353+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/hw8_2_create_pinecone_index.py", line 33, in create_pinecone_index
    import pinecone
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/__init__.py", line 5, in <module>
    raise Exception(
Exception: The official Pinecone python package has been renamed from `pinecone-client` to `pinecone`. Please remove `pinecone-client` from your project dependencies and add `pinecone` instead. See the README at https://github.com/pinecone-io/pinecone-python-client for more information on using the python SDK.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/hw8_2_create_pinecone_index.py", line 39, in create_pinecone_index
    import pinecone_client as pinecone
ModuleNotFoundError: No module named 'pinecone_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hw8_2_create_pinecone_index.py", line 43, in create_pinecone_index
    raise Exception("Could not import either pinecone or pinecone-client. Please install the appropriate package.")
Exception: Could not import either pinecone or pinecone-client. Please install the appropriate package.
[2025-04-17T16:57:36.361+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=hw8_create_pinecone_index, task_id=create_pinecone_index, run_id=manual__2025-04-17T16:52:34.831111+00:00, execution_date=20250417T165234, start_date=20250417T165736, end_date=20250417T165736
[2025-04-17T16:57:36.366+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-17T16:57:36.367+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task create_pinecone_index (Could not import either pinecone or pinecone-client. Please install the appropriate package.; 1315)
Traceback (most recent call last):
  File "/opt/airflow/dags/hw8_2_create_pinecone_index.py", line 33, in create_pinecone_index
    import pinecone
  File "/home/airflow/.local/lib/python3.12/site-packages/pinecone/__init__.py", line 5, in <module>
    raise Exception(
Exception: The official Pinecone python package has been renamed from `pinecone-client` to `pinecone`. Please remove `pinecone-client` from your project dependencies and add `pinecone` instead. See the README at https://github.com/pinecone-io/pinecone-python-client for more information on using the python SDK.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/hw8_2_create_pinecone_index.py", line 39, in create_pinecone_index
    import pinecone_client as pinecone
ModuleNotFoundError: No module named 'pinecone_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hw8_2_create_pinecone_index.py", line 43, in create_pinecone_index
    raise Exception("Could not import either pinecone or pinecone-client. Please install the appropriate package.")
Exception: Could not import either pinecone or pinecone-client. Please install the appropriate package.
[2025-04-17T16:57:36.399+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-17T16:57:36.408+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T16:57:36.409+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
